apiVersion: apps/v1
kind: Deployment
metadata: 
  name: k8s-deployment
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: docker.io/priyankass99/k8s-sample-app
        ports: 
        - containerPort: 8081

---

kind: Service
apiVersion: v1
metadata:
  name: sample-app-service
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31000
  type: NodePort